### ISSUE TITLE
Trying to compile

### ISSUE THREAD

**Issue by wolfallein** [gtzhai/linux-driver-usbtmc-gadget#1]
Hi,

thanks for your work. Can you give some tips in how your drive should be compiled?
I'm trying to compile with mainline kernel 5.7. I added your driver to drivers/usb/gadget/legacy and added to Kconfig/Makefile. I'm getting the following errors, and seems there are functions missing in the code. Can you give me some directions?

````
drivers/usb/gadget/legacy/f_tmc.c:1489:1: error: type defaults to ‘int’ in declaration of ‘CONFIGFS_ATTR_STRUCT’ [-Werror=implicit-int]
drivers/usb/gadget/legacy/f_tmc.c:1489:1: warning: parameter names (without types) in function declaration
drivers/usb/gadget/legacy/f_tmc.c:1490:1: warning: data definition has no type or storage class
 1490 | CONFIGFS_ATTR_OPS(f_tmc_opts);
      | ^~~~~~~~~~~~~~~~~
drivers/usb/gadget/legacy/f_tmc.c:1490:1: error: type defaults to ‘int’ in declaration of ‘CONFIGFS_ATTR_OPS’ [-Werror=implicit-int]
drivers/usb/gadget/legacy/f_tmc.c:1490:1: warning: parameter names (without types) in function declaration
drivers/usb/gadget/legacy/f_tmc.c:1501:3: error: ‘struct configfs_item_operations’ has no member named ‘show_attribute’
 1501 |  .show_attribute = f_tmc_opts_attr_show,
      |   ^~~~~~~~~~~~~~
drivers/usb/gadget/legacy/f_tmc.c:1501:20: error: ‘f_tmc_opts_attr_show’ undeclared here (not in a function)
 1501 |  .show_attribute = f_tmc_opts_attr_show,
      |                    ^~~~~~~~~~~~~~~~~~~~
drivers/usb/gadget/legacy/f_tmc.c:1502:3: error: ‘struct configfs_item_operations’ has no member named ‘store_attribute’
 1502 |  .store_attribute = f_tmc_opts_attr_store,
      |   ^~~~~~~~~~~~~~~
drivers/usb/gadget/legacy/f_tmc.c:1502:21: error: ‘f_tmc_opts_attr_store’ undeclared here (not in a function)
 1502 |  .store_attribute = f_tmc_opts_attr_store,
      |                     ^~~~~~~~~~~~~~~~~~~~~
drivers/usb/gadget/legacy/f_tmc.c:1532:15: error: variable ‘f_tmc_opts_pnp_string’ has initializer but incomplete type
 1532 | static struct f_tmc_opts_attribute f_tmc_opts_pnp_string =
      |               ^~~~~~~~~~~~~~~~~~~~
drivers/usb/gadget/legacy/f_tmc.c:1533:2: error: implicit declaration of function ‘__CONFIGFS_ATTR’; did you mean ‘CONFIGFS_ATTR’? [-Werror=implicit-function-declaration]
 1533 |  __CONFIGFS_ATTR(pnp_string, S_IRUGO | S_IWUSR,
      |  ^~~~~~~~~~~~~~~
      |  CONFIGFS_ATTR
drivers/usb/gadget/legacy/f_tmc.c:1533:18: error: ‘pnp_string’ undeclared here (not in a function); did you mean ‘usb_string’?
 1533 |  __CONFIGFS_ATTR(pnp_string, S_IRUGO | S_IWUSR,
      |                  ^~~~~~~~~~
      |                  usb_string
drivers/usb/gadget/legacy/f_tmc.c:1572:15: error: variable ‘f_tmc_opts_q_len’ has initializer but incomplete type
 1572 | static struct f_tmc_opts_attribute f_tmc_opts_q_len =
      |               ^~~~~~~~~~~~~~~~~~~~
drivers/usb/gadget/legacy/f_tmc.c:1573:18: error: ‘q_len’ undeclared here (not in a function)
 1573 |  __CONFIGFS_ATTR(q_len, S_IRUGO | S_IWUSR, f_tmc_opts_q_len_show,
      |                  ^~~~~
drivers/usb/gadget/legacy/f_tmc.c:1577:24: error: invalid use of undefined type ‘struct f_tmc_opts_attribute’
 1577 |  &f_tmc_opts_pnp_string.attr,
      |                        ^
drivers/usb/gadget/legacy/f_tmc.c:1578:19: error: invalid use of undefined type ‘struct f_tmc_opts_attribute’
 1578 |  &f_tmc_opts_q_len.attr,
      |                   ^
drivers/usb/gadget/legacy/f_tmc.c: In function ‘gtmc_alloc_inst’:
drivers/usb/gadget/legacy/f_tmc.c:1601:6: warning: unused variable ‘status’ [-Wunused-variable]
 1601 |  int status = 0;
      |      ^~~~~~
drivers/usb/gadget/legacy/f_tmc.c: At top level:
drivers/usb/gadget/legacy/f_tmc.c:1532:36: error: storage size of ‘f_tmc_opts_pnp_string’ isn’t known
 1532 | static struct f_tmc_opts_attribute f_tmc_opts_pnp_string =
      |                                    ^~~~~~~~~~~~~~~~~~~~~
drivers/usb/gadget/legacy/f_tmc.c:1572:36: error: storage size of ‘f_tmc_opts_q_len’ isn’t known
 1572 | static struct f_tmc_opts_attribute f_tmc_opts_q_len =
      |                                    ^~~~~~~~~~~~~~~~
drivers/usb/gadget/legacy/f_tmc.c: In function ‘tmc_ioctl’:
drivers/usb/gadget/legacy/f_tmc.c:969:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
  969 |   {
      |   ^
drivers/usb/gadget/legacy/f_tmc.c:1008:3: note: here
 1008 |   default:
      |   ^~~~~~~
At top level:
drivers/usb/gadget/legacy/f_tmc.c:1471:12: warning: ‘tmc_bind_config’ defined but not used [-Wunused-function]
 1471 | static int tmc_bind_config(struct usb_configuration *c)
      |            ^~~~~~~~~~~~~~~
drivers/usb/gadget/legacy/f_tmc.c:448:12: warning: ‘tmc_queue_req’ defined but not used [-Wunused-function]
  448 | static int tmc_queue_req(struct usb_ep *ep,
      |            ^~~~~~~~~~~~~
````
